private_proj/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'private_proj.views.index'),
    url(r'^surm/', include('surm.urls')),
    url(r'^accounts/profile/', 'private_proj.views.profile'),
    url(r'^accounts/(?P<user_id>\d+)/', 'private_proj.views.account_info'),
   
    url(r'^admin/', include(admin.site.urls)),
)

surm/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('surm.views',
    url(r'^$', 'index'),
    url(r'^cre_group/', 'cre_group'),
    url(r'^(?P<group_id>\d+)/$', 'group_index'),
    url(r'^(?P<group_id>\d+)/add_group_member', 'add_group_member'),
    url(r'^(?P<group_id>\d+)/settings', 'group_settings'),
    url(r'^(?P<group_id>\d+)/(?P<tag_id>\d+)/$', 'tag_filtering'),
    url(r'^(?P<group_id>\d+)/favorite', 'my_favorite'),
    url(r'^(?P<group_id>\d+)/get_resourcetitle_error', 'get_resourcetitle_error'),
    
    url(r'^accounts/', include('registration.backends.default.urls')),
)

surm/models.py
# -*- coding: utf-8 -*-
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms

# グループ
class Group(models.Model):
    name = models.CharField('Name', max_length=100)
    created = models.DateTimeField('Created', auto_now_add=True)
    explain = models.CharField('Explain', max_length=100, null=True, blank=True)
    creater = models.ForeignKey(User)

# 参加しているグループ
class JoinGroup(models.Model):
    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    joined = models.DateTimeField('Joined', auto_now_add=True)

# リソース
class Resource(models.Model):
    name = models.CharField('Name', max_length=100)
    url = models.URLField('URL', max_length=100)
    creater = models.ForeignKey(User)
    created = models.DateTimeField('Created', auto_now_add=True)
    group = models.ForeignKey(Group)
    memo = models.TextField('Memo', null=True, blank=True)
    view = models.IntegerField('View', default=0)

# どのグループのどのリソースがどのユーザに閲覧されたかを記録
class ResourceUserView(models.Model):
    group = models.ForeignKey(Group)
    resource = models.ForeignKey(Resource)
    user = models.ForeignKey(User)

# どのグループのどのリソースがどのユーザにお気に入りにされたかを記録
class ResourceUserFavorite(models.Model):
    group = models.ForeignKey(Group)
    resource = models.ForeignKey(Resource)
    user = models.ForeignKey(User)
    favorited = models.DateTimeField('Favorited', auto_now_add=True)

# タグ
class Tag(models.Model):
    group = models.ForeignKey(Group)
    tag = models.CharField('Name', max_length=100)
    registered = models.DateTimeField('Registered', auto_now_add=True)

# どのタグがどのグループのどのリソースに付いているのかを記録
class TagResource(models.Model):
    group = models.ForeignKey(Group)
    resource = models.ForeignKey(Resource)
    tag = models.ForeignKey(Tag)

# ユーザの行動のログを記録
class ActionHistory(models.Model):
    KIND_CHOICES = (
        ('group_create', 'Group Create'),
        ('group_join', 'Group Join'),
        ('group_modify', 'Group Modify'),
        ('group_delete', 'Group Delete'),
        ('resource_post', 'Resource Post'),
        ('resource_view', 'Resource View'),
        ('resource_favorite', 'Resource Favorite'),
        ('resource_delete', 'Resource Delete'),
    )
    
    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    acted = models.DateTimeField('Acted', auto_now_add=True)
    kind = models.CharField('Kind', choices=KIND_CHOICES, max_length=20)
    resource = models.ForeignKey(Resource, null=True, blank=True)

# リソースに対するコメント
class Comment(models.Model):
    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    resource = models.ForeignKey(Resource)
    comment = models.CharField('Comment', max_length=100)
    commented = models.DateTimeField('Commented', auto_now_add=True)

# ------------ フォーム ------------ #

# グループ追加のフォーム
class CreateGroupForm(forms.Form):
    name = forms.CharField(max_length=100)
    explain = forms.CharField(required=False, max_length=100, widget=forms.Textarea)

# リソース追加のフォーム
class AddResourceForm(forms.Form):
#     name = forms.CharField(max_length=100)
    url = forms.URLField(max_length=100, label='URL')
    memo = forms.CharField(required=False, max_length=200, widget=forms.Textarea, label='Memo (Optional)')

# リソース追加のフォーム(エラーが出た時の例外)
class AddResourceExceptForm(forms.Form):
    name = forms.CharField(max_length=100)
    url = forms.URLField(max_length=100, label='URL')
    memo = forms.CharField(required=False, max_length=200, widget=forms.Textarea, label='Memo (Optional)')

# グループ設定のフォーム
class GroupSettingsForm(forms.Form):
    group_name = forms.CharField(required=False, max_length=100, label='Group Name (Optional)')
    explain = forms.CharField(required=False, max_length=100, widget=forms.Textarea, label='Explain (Optional)')

# コメント追加のフォーム
class CommentForm(forms.Form):
    comment = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'placeholder':'Comment'}))

surm/views.py
# -*- coding: utf-8 -*-
import urllib2
import re
import json

from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse, Http404
from surm.models import Group, JoinGroup, Resource, ResourceUserView, ResourceUserFavorite, Tag, TagResource, ActionHistory, Comment, CreateGroupForm, AddResourceForm, AddResourceExceptForm, GroupSettingsForm, CommentForm

from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# !【メモ】メール送信用クラス メール送信が1ヶ所のみなので今のところコメントアウト
# class Email:
#     def __init__(self, group, user, email_template, resource_name):
#         self.group = group
#         self.user = user
#         self.resource_name = resource_name
#     def sendemail(self):
#         join_users = User.objects.filter(joingroup__group__exact=group)
#         join_users_email = []
#         for join_user in join_users:
#             join_users_email.append(join_users.email)
#         plaintext = get_template(email_template)
#         sender = 'tomita.research@gmail.com'
#         group = self.group
#         user = self.user
#         resource_name = self.resource_name
#         recipients = join_users_email
#         subject = u'リソースが投稿されました'
#         d = Context({'group': group, 'user': user, 'resource_name': resource_name})
#         textcontent = plaintext.render(d)
#         msg = EmailMultiAlternatives(subject, textcontent, sender, recipients)
#         msg.send()
    


def index(request):
    
    message = None
    
    if request.method == 'POST':
        if 'name' in request.POST:
            form = CreateGroupForm(request.POST)
            if form.is_valid():
                g = Group(name=form.cleaned_data['name'], creater=request.user, explain=form.cleaned_data['explain'])
                g.save()
                jg = JoinGroup(user=request.user, group=g)
                jg.save()
                
                new_actionhistory = ActionHistory(user=request.user, group=g, kind='group_create')
                new_actionhistory.save()
                
            else:
                return HttpResponseRedirect('/surm/cre_group/')
        if 'dlt_group_id' in request.POST:
            # グループ自体と，関連するデータを全て削除
            print request.POST['dlt_group_id']
            group = get_object_or_404(Group, pk=request.POST['dlt_group_id'])
            group_name = group.name
            
            dlt_resourceuserview = ResourceUserView.objects.filter(group=group)
            dlt_resourceuserview.delete()
            
            dlt_resource = Resource.objects.filter(group=group)
            dlt_resource.delete()
            
            dlt_joingroup = JoinGroup.objects.filter(group=group)
            dlt_joingroup.delete()
            
            group.delete()
            
            new_actionhistory = ActionHistory(user=request.user, group=group, kind='group_delete')
            new_actionhistory.save()
            
            message = u'グループ ' +group_name+ u' を削除しました．'
    
    try:
        mygroups = Group.objects.filter(joingroup__user__exact=request.user)
        my_actionhistories = ActionHistory.objects.filter(user=request.user).order_by('-acted')[:5]
        print mygroups
        print my_actionhistories
        context = {
            'title': 'index',
            'mygroups': mygroups,
            'my_actionhistories': my_actionhistories,
            'message': message,
        }
    except:
        context = {
            'title': 'index'
        }
    return render(request, 'surm/index.html', context)


def cre_group(request):
    form = CreateGroupForm()
    context = {
        'title': 'Create Group',
        'form': form
    }
    return render(request, 'surm/cre_group.html', context)


def group_index(request, group_id):

    message = None
    search_filtering_resources = None
    search_result = None
    
    group = get_object_or_404(Group, pk=group_id)
    join_users = User.objects.filter(joingroup__group__exact=group)
    
    comment_form_flg = False
    
    # グループに参加していないユーザからのアクセスにはForbiddenを返す
    member_flg = False
    for join_user in join_users:
        if request.user == join_user:
            member_flg = True
            break
    if member_flg == False:
        return HttpResponseForbidden()
    
    # POSTされた値によって処理を変化
    if request.method == 'POST': # まずPOSTされたか判定
    
        if 'ajax' in request.POST: # ajaxがrequest.POST内にあれば以下の処理
            print 'ajax success'
            form = AddResourceForm()
            select_resource = get_object_or_404(Resource, pk=request.POST['ajax'])
            print select_resource
            select_resource.view += 1
            select_resource.save()
            new_user_resource_view = ResourceUserView.objects.get_or_create(group=group, resource=select_resource, user=request.user)
            new_actionhistory = ActionHistory(user=request.user, group=group, kind='resource_view', resource=select_resource)
            new_actionhistory.save()
            
        elif 'name' in request.POST: # get_resourcetitle_errorからポストされた場合
            add_resource_except_form = AddResourceExceptForm(request.POST)
            if add_resource_except_form.is_valid():
            
                memos = re.split(r'\[(.*)\]', add_resource_except_form.cleaned_data['memo']) # 正規表現でタグ以降だけ抽出
                
                try: # メモにタグしか書かなかった場合，IndexErrorを吐くのでそのときは例外処理
                    new_resource = Resource(name=add_resource_except_form.cleaned_data['name'], url=add_resource_except_form.cleaned_data['url'], creater=request.user, memo=memos[2], group=group)
                except IndexError:
                    new_resource = Resource(name=add_resource_except_form.cleaned_data['name'], url=add_resource_except_form.cleaned_data['url'], creater=request.user, group=group)
                
                new_resource.save()
                
                new_actionhistory = ActionHistory(user=request.user, group=group, kind='resource_post', resource=new_resource)
                new_actionhistory.save()
            
            form = AddResourceForm()
            
        elif 'url' in request.POST: # urlがrequest.POST内にあれば以下の処理
            form = AddResourceForm(request.POST)
            if form.is_valid(): # バリデート
                # ページタイトルはre，urllibを使ってURLから取得
                posted_url_info = urllib2.urlopen(form.cleaned_data['url']).read()
                pattern = re.compile(r'<title>(.*)</title>', re.IGNORECASE)
                title = pattern.findall(posted_url_info)
                memos = re.split(r'\[(.*)\]', form.cleaned_data['memo']) # 正規表現でタグ以降だけ抽出
                if len(title) == 0: # titleに何も入ってない(リソースタイトルを取って来れなかった場合)
                    return redirect('surm.views.get_resourcetitle_error', group_id=group.id)
                try: # メモにタグしか書かなかった場合，IndexErrorを吐くのでそのときは例外処理
                    new_resource = Resource(name=title[0].decode('utf-8'), url=form.cleaned_data['url'], creater=request.user, group=group, memo=memos[2])
                except IndexError:
                    new_resource = Resource(name=title[0].decode('utf-8'), url=form.cleaned_data['url'], creater=request.user, group=group)
                new_resource.save()
                
                new_actionhistory = ActionHistory(user=request.user, group=group, kind='resource_post', resource=new_resource)
                new_actionhistory.save()
                
                # 入力されたタグをタグテーブルへ
                registered_tags = re.findall(r'\[(.*?)\]', form.cleaned_data['memo'])
                print registered_tags
                for registered_tag in registered_tags:
                    new_tag = Tag.objects.get_or_create(group=group, tag=registered_tag)
                    print new_tag[0]
                    #new_tag.save()
                    new_tag_resource = TagResource.objects.get_or_create(group=group, resource=new_resource, tag=new_tag[0])
                    #new_tag_resource.save()
                
                ## グループのメンバーにメール通知 ##
                ## リソース削除された時等，よく使う事になるのでこの部分は関数化できない？
                
                join_users_email = []
                for join_user in join_users:
                    join_users_email.append(join_user.email)
                
                # テンプレート読み込み
                plaintext = get_template('email.txt')
                
                # テンプレートに流し込む情報を整理
                sender = 'tomita.research@gmail.com'
                group = group
                user = request.user
                resource_name = title[0].decode('utf-8')
                
                # 送信先
                recipients = join_users_email
                subject = u'リソースが投稿されました'
                
                # テンプレートに整理した情報を流し込む
                d = Context({'group': group, 'user': user, 'resource_name': resource_name})
                textcontent = plaintext.render(d)
                
                # メール送信
                msg = EmailMultiAlternatives(subject, textcontent, sender, recipients)
                msg.send()
                
                form = AddResourceForm()
                
        elif 'add_user_id' in request.POST: # add_user_idがrequest.POST内にあれば以下の処理
            form = AddResourceForm()
            print request.POST['add_user_id']
            add_user = get_object_or_404(User, pk=request.POST['add_user_id'])
            new_join_user = JoinGroup(user=add_user, group=group)
            new_join_user.save()
            
            new_actionhistory = ActionHistory(user=add_user, group=group, kind='group_join')
            new_actionhistory.save()
            
        elif 'favorite_resource_id' in request.POST:
            print 'favorite resource'
            form = AddResourceForm()

templates/surm/add_group_member.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block additional_static %}

{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
    <ol class="breadcrumb">
        <li><a href="{% url 'surm.views.index' %}">{{ user.username }} - SURM</a></li>
        <li><a href="{% url 'surm.views.group_index' group_id=group.id %}">{{ group.name }}</a></li>
        <li class="active">{{ title }}</li>
    </ol>
{% endblock %}

{% block content %}
{% if user.id == group.creater.id %}
    <h4>参加していないユーザ</h4>
    {% if all_users %}
    <table class="table table-striped">
        {% for all_user in all_users %}
        <tr>
            <td>
                {{ all_user.username }}
            </td>
            <td>
                <form action="{% url 'surm.views.group_index' group_id=group.id %}" method="post" >
                    {% csrf_token %}
                    <input type="hidden" name="add_user_id" value="{{ all_user.id }}" />
                    <input type="submit" class="btn btn-xs btn-surm" value="追加" />
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>※ 全てのユーザが参加しています</p>
    {% endif %}
{% else %}
<p>アクセス権限がありません</p>
{% endif %}
{% endblock %}

templates/surm/group_index.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block additional_static %}
<link href="{% static 'css/group_index.css' %}" rel="stylesheet">
<script src="{% static 'js/csrf_token_ajax.js' %}"></script>
<script src="{% static 'js/group_index.js' %}"></script>
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
    {% if message %}
        <p class="message">{{ message }}</p>
    {% endif %}
    <ol class="breadcrumb">
        <li><a href="{% url 'surm.views.index' %}">{{ user.username }} - SURM</a></li>
        <li class="active">{{ title }}</li>
    </ol>
{% endblock %}

{% block content %}
    {% block top-content %}
    <h2><a href="{% url 'surm.views.group_index' group_id=group.id %}" class="group_name">{{ group.name }}</a></h2>
    {% if group.explain %}
    <p>{{ group.explain }}</p>
    {% endif %}
    {% endblock %}
    <div class="row">
        <div class="col-sm-2 left-content">
            {% block left-content %}
            <div class="group_info">
                {% if user.id == group.creater.id %}
                <a href="{% url 'surm.views.group_settings' group_id=group.id %}" class="btn btn-xs btn-surm"><i class="fa fa-cog"></i> グループの設定</a>
                {% endif %}
            </div>
            <div class="group_info">
                <ul class="list-inline">
                    <li><h4>メンバー: {{ join_users | length }}人</h4></li>
                {% if user.is_superuser or user.id == group.creater.id %}
                    <li><a href="{% url 'surm.views.add_group_member' group_id=group.id %}" class="btn btn-xs btn-surm add_member_btn"><i class="fa fa-users"></i> 追加</a></li>
                {% endif %}
                </ul>
                <ul class="join_users">
                    {% for join_user in join_users %}
                        <li><span class="username">{{ join_user.username }}</span>
                            {% if join_user.id == group.creater.id %}
                                <span class="label label-xs label-danger">管理者</span>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            
            <div class="registered_tags">
                <h4>登録されたタグ</h4>
                <ul>
                    {% for group_tag in group_tags %}
                        <li><a href="{% url 'surm.views.tag_filtering' group_id=group.id tag_id=group_tag.id %}">{{ group_tag.tag }}({{ group_tag.tagresource_set.all.count }})</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% endblock %}
            
            <div class="search_resource">
                <h4>リソース検索</h4>
                <form action="{% url 'surm.views.group_index' group_id=group.id %}" method="get" class="form resource_add_form">
                {% csrf_token %}
                <input type="text" name="q" class="form-control search_input" />
                <button type="submit" class="btn btn-default btn-sm">Search</button>
            </form>
            </div>
        </div>
        
        <div class="col-sm-7 center-content">
            {% block center-content %}
            {% block except-resource-list-content %}
            
            <h3 class="headding_3 post_resource_headding">リソースの投稿</h3>
            <hr class="headding_3_underline" />
            <p>URLを入力すればリソースタイトルは自動入力されます．</p>
            <p>Memo内で付与したいタグを[]で囲む事でタグを付与する事ができます．</p>
            <p>(例: [Django][Python][チュートリアル]Djangoのチュートリアルです．)</p>
            <form action="{% url 'surm.views.group_index' group_id=group.id %}" method="post" class="form resource_add_form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            
            {% if search_result %}
            <h3 class="headding_3">「<span class="query">{{ search_result }}</span>」の検索結果</h3>
            {% else %}
            <h3 class="headding_3">投稿されたリソース一覧</h3>
            {% endif %}
            <hr class="headding_3_underline" />
            {% endblock %}
            {% block resource-list-content %}
            {% if resources %}
                <ul class="posted_resources">
                {% for resource in resources %}
                    <li class="posted_resource" id="resource{{ resource.id }}">
                        <a class="link_btn post_resource_btn" id="{{ resource.id }}" href="{{ resource.url }}" target="_blank">{{ resource.name }}</a>
                        {% if user.id == resource.creater.id %}
                        <button class="dlt_button icon_button" id="{{ resource.id }}"><i class="fa fa-times"></i></button>
                        <div class="dlt_confirm">
                            <form action="{% url 'surm.views.group_index' group_id=group.id%}" method="post" class="form confirm">
                                {% csrf_token %}
                                本当に削除してもよろしいですか？
                                <input type="hidden" name="dlt_resource_id" value="{{ resource.id }}" />
                                <input type="submit" class="btn btn-xs btn-danger" value="はい" />
                            </form>
                        </div>
                        {% endif %}
                        <ul class="posted_resource_info">
                            <li> 
                                <button class="fav_button icon_button" id="{{ resource.id }}"><i class="fa fa-star"></i></button>{{ resource.resourceuserfavorite_set.all.count }}　<span class="label label-danger views">{% if resource.view >= 2 %}{{ resource.view }} Views{% else %}{{ resource.view }} View{% endif %}</span>
                            </li>
                            <li>
                                <span class="memo">{% if resource.memo %}{{ resource.memo }}{% else %}{% endif %}</span>
                                {% if user.id == resource.creater.id %}
                                <button class="memo_edit icon_button" id="{{ resource.id }}" title="メモの編集"><i class="fa fa-pencil"></i></button>
                                {% endif %}
                                <div class="memo_edit_parts">
                                    <input type="text" class="memo_edit_area form-control" id="{{ resource.id }}"/>
                                    <button class="btn btn-sm btn-default complete_button">Complete</button>
                                    <button class="btn btn-sm btn-default cancel_button">Cancel</button>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-tags"></i>
                                {% for tag in resource.tagresource_set.all %}
                                    <span class="tags">{{ tag.tag.tag }}{% if forloop.last == False %} {% endif %}</span>
                                {% endfor %}
                            </li>
                            <li><i class="fa fa-eye"></i>
                                {% for read_user in resource.resourceuserview_set.all %}
                                    {{ read_user.user.username }}{% if forloop.last == False %},{% endif %}
                                {% endfor %}
                            </li>
                            <li class="posted_user">{{ resource.created }} - {{ resource.creater.username }}</li>
                        </ul>
                        <div class="comments_area">
                            <form action="{% url 'surm.views.group_index' group_id=group.id %}" method="post" class="form-inline add_comment_form">
                                {% csrf_token %}
                                {% bootstrap_form comment_form %}
                                <input type="hidden" name="resource_id" value="{{ resource.id }}" />
                                <input type="submit" class="btn btn-default comment_submit" value="Submit"/>
                            </form>
                                {% if resource.comment_set.all.count > 0 %}
                                <p class="show_comment">コメントを表示する({{ resource.comment_set.all.count }})</p>
                                <div class="comments">
                                    <ul>
                                    {% for resource_comment in resource.comment_set.all|dictsortreversed:"commented" %}
                                        <li>{{ forloop.revcounter }}　{{ resource_comment.user.username }} : {{ resource_comment.comment }}</li>
                                        {% if forloop.last == False %}
                                        <li><hr class="comment_pertition" /></li>
                                        {% endif %}
                                    {% endfor %}
                                    </ul>
                                </div>
                                {% endif %}
                        </div>
                        <hr />
                    </li>
                {% endfor %}
                </ul>
                <div class="moreread" id="more1">
                    <a href="javascript:void(0)" class="resource_moreread" id="1">もっと読む</a>
                </div>
                <div class="pagination">
                    <span class="step-links">
                        {% if resources.has_previous %}
                            <a href="?page={{ resources.previous_page_number }}">previous</a>
                        {% endif %}
                        
                        <span class="current">
                            Page {{ resources.number }} of {{ resources.paginator.num_pages }}.
                        </span>
                        
                        {% if resources.has_next %}
                            <a href="?page={{ resources.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% else %}
                <p>投稿されたリソースはありません</p>
            {% endif %}
            {% endblock %}
            {% endblock %}
        </div>
        
        <div class="col-sm-3 right-content">
            {% block right-content %}
            <div class="my_favorite">
                <h4 class="my_favorite_headding">自分のお気に入り</h4>
                <table class="table my_favorite_list">
                    <tr>
                        <th>リソース名</th>
                        <th>タグ</th>
                    </tr>
                    {% for my_favorite_resource in my_favorite_resources %}
                    <tr>
                        <td><a href="{{ my_favorite_resource.resource.url }}" class="post_resource_btn" id="{{ my_favorite_resource.resource.id }}" target="_blank">{{ my_favorite_resource.resource.name }}</a></td>
                        <td>
                            {% for tag in my_favorite_resource.resource.tagresource_set.all %}
                                {{ tag.tag.tag }}{% if forloop.last == False %},{% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                <a href="{% url 'surm.views.my_favorite' group_id=group.id %}" class="btn btn-default btn-xs read_more_btn">もっと見る</a>
            </div>
            
            <div class="favorite_info">
                <h4>お気に入りが多いリソース</h4>
                <table class="table">
                    <tr>
                        <th>リソース</th>
                        <th><i class="fa fa-star"></i></th>
                    </tr>
                    {% for resource in resources %}
                    {% if resource.resourceuserfavorite_set.all.count > join_users_count_half %}
                    <tr>
                        <td><a href="{{ resource.url }}" class="post_resource_btn" id="{{ resource.id }}" target="_blank">{{ resource.name }}</a></td>
                        <td>{{ resource.resourceuserfavorite_set.all.count }}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
            
            <div class="recent_comments">
                <h4>最近コメントされたリソース</h4>
                <ul class="recent_comments_resources">
                    {% for recent_comment in recent_comments %}
                    <li class="recent_comments_resource">
                        <a href="#resource{{ recent_comment.resource.id }}">{{ recent_comment.resource.name }}</a>
                        <ul class="recent_comments_resource_commented">
                            <li>{{ recent_comment.commented }}</li>
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/surm/my_favorite.html
{% extends "surm/group_index.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block additional_static_from_index %}
<link rel="stylesheet" href="{% static 'css/my_favorite.css' %}" />
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
    {% if message %}
        <p class="message">{{ message }}</p>
    {% endif %}
    <ol class="breadcrumb">
        <li><a href="{% url 'surm.views.index' %}">{{ user.username }} - SURM</a></li>
        <li><a href="{% url 'surm.views.group_index' group_id=group.id %}">{{ group.name }}</a></li>
        <li class="active">{{ title }}</li>
    </ol>
{% endblock %}

{% block center-content %}
<h3 class="headding_3">{{ user.username }}のお気に入りリソース</h3>
<div class="my_favorite">
    <table class="table my_favorite_list">
        <tr>
            <th>リソース名</th>
            <th>タグ</th>
            <th></th>
        </tr>
        {% for my_favorite_resource in my_favorite_resources %}
        <tr>
            <td><a href="{{ my_favorite_resource.resource.url }}" class="post_resource_btn" id="{{ my_favorite_resource.resource.id }}" target="_blank">{{ my_favorite_resource.resource.name }}</a></td>
            <td>
                {% for tag in my_favorite_resource.resource.tagresource_set.all %}
                    {{ tag.tag.tag }}{% if forloop.last == False %},{% endif %}
                {% endfor %}
            </td>
            <td>
                <form action="{% url 'surm.views.my_favorite' group_id=group.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="favorite_resource_id" value="{{ my_favorite_resource.resource.id }}"/>
                    <button type="submit" class="cancel_favorite_btn"><i class="fa fa-times"></i></button>
                </form>
                
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

{% block right-content %}
<div class="favorite_info">
    <h4>お気に入り履歴</h4>
    <table class="table">
        <tr>
            <th></th>
            <th>リソース名</th>
        </tr>
        {% for favorite_resource in favorite_resources_history %}
        <tr>
            <td>{{ favorite_resource.user.username }}</td>
            <td><a href="{{ favorite_resource.resource.url }}" class="post_resource_btn" id="{{ favorite_resource.resource.id }}" target="_blank">{{ favorite_resource.resource.name }}</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}